# Notification Service Configuration
spring.application.name=notification-service

# Run this service on port 8087
server.port=8087

# MongoDB Configuration (using your Atlas cluster + notification_db database)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://eshan:pKLqD1NoGz1UEzJX@cluster0.tluvaip.mongodb.net/notification_db?appName=Cluster0}

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eshanrandunu22@gmail.com
spring.mail.password=aiurquvwyievzgrt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS Mock Mode (set to false when using real Twilio)
sms.mock.enabled=true

# Twilio Configuration (real credentials ? but mock is enabled, so not used unless mock=false)

twilio.account_sid=ACbb3d340ac45bac5cd898719f80850391
twilio.auth_token=bea5ff2321d7ec350d44b1b8a24d1e50
twilio.phone_number=+94769215392
