spring.application.name=notification-service
# Run this service on port 8086
server.port=8086

# Database Configuration for notification Service
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update