spring.application.name=api-gateway
# Run this service on port 8080
server.port=8080

# Database Configuration for api gateway Service
spring.datasource.url=jdbc:mysql://localhost:3306/api_gateway_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update