server.port=8085
server.servlet.context-path=/
server.error.include-stacktrace=never
server.error.include-exception=false

spring.application.name=payment-service
spring.data.mongodb.uri=${PAYMENT_MONGODB_URI:mongodb://localhost:27017/payment_db}

payment.gateway.provider=demo-sandbox
payment.currency=LKR
payment.minimum-amount=100.0
payment.maximum-amount=50000.0

services.appointment.url=${APPOINTMENT_SERVICE_URL:http://localhost:8083}

logging.level.com.medilink.paymentservice=DEBUG
