server.port=8085
server.servlet.context-path=/
server.error.include-stacktrace=never
server.error.include-exception=false

spring.application.name=payment-service
spring.mongodb.uri=mongodb+srv://medilinkUser:medilinkUser123@appointment-payment-ser.jcrrqm0.mongodb.net/payment_db?retryWrites=true&w=majority&appName=Appointment-payment-service

payment.gateway.provider=demo-sandbox
payment.currency=LKR
payment.minimum-amount=100.0
payment.maximum-amount=50000.0

services.appointment.url=http://localhost:8083

logging.level.com.medilink.paymentservice=DEBUG
