server.port=8085
server.servlet.context-path=/
server.error.include-stacktrace=never
server.error.include-exception=false

spring.application.name=payment-service
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://medilinkUser:medilinkUser123@appointment-payment-ser.jcrrqm0.mongodb.net/payment_db?retryWrites=true&w=majority&appName=Appointment-payment-service}

payment.gateway.provider=stripe-test
payment.currency=LKR
payment.minimum-amount=100.0
payment.maximum-amount=50000.0
payment.stripe.secret-key=${STRIPE_SECRET_KEY:}
payment.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
payment.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:5173}
payment.stripe.success-url=${payment.frontend-base-url}/patient/payment?appointment_id={APPOINTMENT_ID}&checkout=success
payment.stripe.cancel-url=${payment.frontend-base-url}/patient/payment?appointment_id={APPOINTMENT_ID}&checkout=cancel

services.appointment.url=${SERVICES_APPOINTMENT_URL:http://localhost:8084/api}
services.notification.url=${SERVICES_NOTIFICATION_URL:http://localhost:8087}

logging.level.com.medilink.paymentservice=DEBUG
