server.port=8083
server.servlet.context-path=/api

spring.application.name=appointment-service
spring.data.mongodb.uri=${APPOINTMENT_MONGODB_URI:mongodb://localhost:27017/appointment_db}

logging.level.root=INFO
