server.port=8083
server.servlet.context-path=/api

spring.application.name=appointment-service
spring.mongodb.uri=mongodb+srv://medilinkUser:medilinkUser123@appointment-payment-ser.jcrrqm0.mongodb.net/appointment_db?retryWrites=true&w=majority&appName=Appointment-payment-service

services.patient.url=http://localhost:8086
services.doctor.url=http://localhost:8084

logging.level.root=INFO
