# Docker-specific configuration
spring.data.mongodb.host=mongo-auth
spring.data.mongodb.port=27017

services.doctor.url=http://doctor-service:8083
services.patient.url=http://patient-service:8082
services.appointment.url=http://appointment-service:8084
services.payment.url=http://payment-service:8085
services.telemedicine.url=http://telemedicine-service:8086
services.notification.url=http://notification-service:8087