# Patient Service Configuration
spring.application.name=patient-service

# Run this service on port 8086
server.port=8086

# MongoDB Configuration (using your Atlas cluster + patient_db database)
spring.data.mongodb.uri=mongodb+srv://eshan:pKLqD1NoGz1UEzJX@cluster0.tluvaip.mongodb.net/patient_db?appName=Cluster0

# Cloudinary Configuration for Medical Report PDF Uploads
cloudinary.cloud_name=Root
cloudinary.api_key=986534418514183
cloudinary.api_secret=2fmnNTHsKyB4YL1BXSXwx_jcRC8

# Max File Size for Uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB